/* ============================================================
   대한장애인체육회 장애인전용체육시설 데이터 (73개)
   좌표: 네이버 Geocoding API 사전 지오코딩 (2026-05-26 갱신)
   전체 73개 / naver_full 68개 / naver_partial 1개
          / naver_name 0개 / naver_district 4개
          / region_centroid 0개 / 기존좌표유지 0개
   ============================================================ */
window.HWPC_FACILITIES = [
  {
    "id": "hwpc_1",
    "name": "SRC 서울센터",
    "region": "서울",
    "district": "관악구",
    "address": "서울특별시 관악구 보라매로 44",
    "phone": "02-871-3636",
    "website": "seoulsrc.com",
    "org": "사복) SRC",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 37.4931756,
    "lng": 126.9274006,
    "disability_types": [
      "자폐성",
      "시각",
      "지체",
      "기타"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_2",
    "name": "서울곰두리체육센터",
    "region": "서울",
    "district": "송파구",
    "address": "서울시 송파구 동남로 271",
    "phone": "02-404-6240",
    "website": "www.sgsc.or.kr",
    "org": "사)한국시각장애인연합회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.5004957,
    "lng": 127.1354641,
    "disability_types": [
      "뇌병변",
      "청각",
      "지적"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_3",
    "name": "서부재활체육센터",
    "region": "서울",
    "district": "은평구",
    "address": "서울특별시 은평구 갈현로11길 30",
    "phone": "02-388-6622",
    "website": "www.sbsports.or.kr",
    "org": "사복)엔젤스헤이븐(은평천사원)",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 37.6056099,
    "lng": 126.9067178,
    "disability_types": [
      "뇌병변",
      "시각",
      "지체",
      "청각",
      "지적",
      "자폐성",
      "기타"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_4",
    "name": "동천재활체육센터",
    "region": "서울",
    "district": "노원구",
    "address": "서울특별시 노원구 노원로18길 41",
    "phone": "02-949-9114",
    "website": "www.dcsports.co.kr",
    "org": "사복)동천학원",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.6445781,
    "lng": 127.0728729,
    "disability_types": [
      "자폐성",
      "시각",
      "뇌병변",
      "지적",
      "청각",
      "지체"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_5",
    "name": "마포푸르메스포츠센터",
    "region": "서울",
    "district": "마포구",
    "address": "서울특별시 마포구 월드컵북로 494",
    "phone": "02-6070-9270",
    "website": "www.purmesports.or.kr",
    "org": "재단법인 푸르메",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.5846589,
    "lng": 126.8805264,
    "disability_types": [
      "시각",
      "뇌병변",
      "지적"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_6",
    "name": "서울수중재활센터",
    "region": "서울",
    "district": "강동구",
    "address": "서울특별시 강동구 고덕로 201",
    "phone": "02-440-5700",
    "website": "www.seoulreports.or.kr",
    "org": "시립서울장애인종합복지관",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 37.5558562,
    "lng": 127.1482802,
    "disability_types": [
      "청각",
      "지적",
      "자폐성",
      "뇌병변",
      "지체",
      "시각",
      "기타"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": true
  },
  {
    "id": "hwpc_7",
    "name": "기쁜우리체육센터",
    "region": "서울",
    "district": "강서구",
    "address": "서울특별시 강서구 허준로 65",
    "phone": "02-3663-8114",
    "website": "www.gibbunsports.or.kr",
    "org": "사복)기쁜우리월드",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.5693631,
    "lng": 126.8487793,
    "disability_types": [
      "지체",
      "뇌병변"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_8",
    "name": "정립회관(체육센터)",
    "region": "서울",
    "district": "광진구",
    "address": "서울특별시 광진구 워커힐로 93",
    "phone": "02-446-1237",
    "website": "www.jeongnip.or.kr",
    "org": "사복)한국소아마비협회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.5510878,
    "lng": 127.0976313,
    "disability_types": [
      "지적",
      "지체",
      "청각",
      "뇌병변",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_9",
    "name": "서부산권장애인스포츠센터",
    "region": "부산",
    "district": "사하구",
    "address": "부산광역시 사하구 낙동남로1233번길 20",
    "phone": "051-203-7780",
    "website": "https:www.sbsd.kr",
    "org": "사)사하스포츠클럽",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 35.1094432,
    "lng": 128.9469,
    "disability_types": [
      "자폐성",
      "지체"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_10",
    "name": "부산곰두리스포츠센터",
    "region": "부산",
    "district": "연제구",
    "address": "부산광역시 연제구 화지로 109",
    "phone": "051-503-6363",
    "website": "www.gomduri.org",
    "org": "사복)양지동산",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 35.1852386,
    "lng": 129.0657322,
    "disability_types": [
      "자폐성",
      "시각",
      "지체",
      "뇌병변"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_11",
    "name": "부산한마음스포츠센터",
    "region": "부산",
    "district": "해운대구",
    "address": "부산광역시 해운대구 세실로 175",
    "phone": "051-709-0700",
    "website": "hmsports.bisco.or.kr",
    "org": "부산시설공단",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 35.1803978,
    "lng": 129.1766873,
    "disability_types": [
      "지적",
      "뇌병변",
      "지체",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_12",
    "name": "대구장애인종합복지관(체육관)",
    "region": "대구",
    "district": "수성구",
    "address": "대구광역시 달서구 파동로51길 26",
    "phone": "053-763-1011",
    "website": "www.dgrc.or.kr",
    "org": "사)국제라이온스 356-A",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 35.858165,
    "lng": 128.630625,
    "disability_types": [
      "뇌병변",
      "자폐성",
      "시각",
      "지체",
      "청각",
      "지적",
      "기타"
    ],
    "geocode_source": "naver_district",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_13",
    "name": "대구광역시 달구벌재활스포츠센터",
    "region": "대구",
    "district": "달서구",
    "address": "대구광역시 달서구 달구벌 대로 291",
    "phone": "053-523-2112",
    "website": "www.dgsports.org",
    "org": "사복)전석복지재단",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 35.829867,
    "lng": 128.532737,
    "disability_types": [
      "시각",
      "뇌병변",
      "지체",
      "청각"
    ],
    "geocode_source": "naver_district",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_14",
    "name": "대구광역시장애인국민체육센터",
    "region": "대구",
    "district": "수성구",
    "address": "대구광역시 수성구 유니버시아드로42",
    "phone": "053-795-8061",
    "website": "dasadgym.or.kr",
    "org": "대구광역시장애인체육회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 35.858165,
    "lng": 128.630625,
    "disability_types": [
      "자폐성",
      "청각"
    ],
    "geocode_source": "naver_partial",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_15",
    "name": "인천광역시장애인체육관",
    "region": "인천",
    "district": "연수구",
    "address": "인천광역시 연수구 앵고개로 130",
    "phone": "032-833-3055",
    "website": "i-gym.or.kr",
    "org": "인천광역시장애인체육회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 37.4124316,
    "lng": 126.659467,
    "disability_types": [
      "뇌병변",
      "자폐성",
      "청각",
      "시각",
      "지체",
      "지적"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_16",
    "name": "인천광역시장애인국민체육센터",
    "region": "인천",
    "district": "연수구",
    "address": "인천광역시 연수구 경원대로 526",
    "phone": "032-719-7044",
    "website": "ic-sports.or.kr",
    "org": "인천광역시장애인체육회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 37.4309078,
    "lng": 126.7018293,
    "disability_types": [
      "지적",
      "뇌병변",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": true
  },
  {
    "id": "hwpc_17",
    "name": "광주광역시장애인종합체육관",
    "region": "광주",
    "district": "북구",
    "address": "광주광역시 북구 북문대로 219",
    "phone": "062-513-0977",
    "website": "www.kjwc.or.kr",
    "org": "재단법인 광주복지재단",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 35.1852509,
    "lng": 126.867887,
    "disability_types": [
      "청각",
      "지적",
      "자폐성",
      "지체",
      "정신",
      "기타"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_18",
    "name": "광주광역시장애인국민체육센터",
    "region": "광주",
    "district": "서구",
    "address": "광주광역시 서구 금화로 278",
    "phone": "062-600-3900",
    "website": "www.gjsad.or.kr",
    "org": "광주광역시장애인체육회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 35.1368102,
    "lng": 126.8790595,
    "disability_types": [
      "지적",
      "자폐성",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_19",
    "name": "대전광역시장애인체육센터",
    "region": "대전",
    "district": "유성구",
    "address": "대전광역시 유성구 덕명로56",
    "phone": "042-610-2975",
    "website": "www.djsiseol.or.kr",
    "org": "대전광역시 시설관리공단",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 36.3573475,
    "lng": 127.3045785,
    "disability_types": [
      "자폐성",
      "지체",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_20",
    "name": "시립산성종합복지관",
    "region": "대전",
    "district": "중구",
    "address": "대전광역시 중구 유등천동로232",
    "phone": "042-586-8033",
    "website": "www.djsswel.or.kr",
    "org": "사)대전시각장애인연합회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 36.3038098,
    "lng": 127.3826733,
    "disability_types": [
      "지체",
      "지적",
      "뇌병변",
      "청각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": true
  },
  {
    "id": "hwpc_21",
    "name": "대전광역시 서구건강체련관",
    "region": "대전",
    "district": "서구",
    "address": "대전광역시 서구 둔산서로 100",
    "phone": "042-488-3054",
    "website": "www.skwelfare.or.kr",
    "org": "사복)미동",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 36.355504,
    "lng": 127.383844,
    "disability_types": [
      "자폐성",
      "지적",
      "청각",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_22",
    "name": "성세체육관",
    "region": "대전",
    "district": "유성구",
    "address": "대전광역시 유성구 유성대로 298",
    "phone": "042-540-3280",
    "website": "www.seongsegym.com",
    "org": "사복)성재원",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 36.362322,
    "lng": 127.356268,
    "disability_types": [
      "뇌병변",
      "지체",
      "지적",
      "시각",
      "자폐성"
    ],
    "geocode_source": "naver_district",
    "verified_at": null,
    "has_weekend": true,
    "is_free": true
  },
  {
    "id": "hwpc_23",
    "name": "유성구장애인종합복지관(체육관)",
    "region": "대전",
    "district": "유성구",
    "address": "대전광역시 유성구 북유성대로 166",
    "phone": "042-822-3687",
    "website": "withway.or.kr",
    "org": "사)한국지체장애인협회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 36.3814356,
    "lng": 127.3233641,
    "disability_types": [
      "자폐성",
      "지체",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_24",
    "name": "대전광역시립 체육재활원",
    "region": "대전",
    "district": "대덕구",
    "address": "대전광역시 대덕구 대화로 10",
    "phone": "042-631-9889",
    "website": "www.djsrc.or.kr",
    "org": "사)대전장애인단체총연합회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 36.3682408,
    "lng": 127.4190858,
    "disability_types": [
      "뇌병변",
      "자폐성",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_25",
    "name": "대덕구장애인종합복지관",
    "region": "대전",
    "district": "대덕구",
    "address": "대전광역시 대덕구 신탄진로 77",
    "phone": "042-637-8848",
    "website": "www.ddwelfare.or.kr",
    "org": "카톨릭사회복지회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 36.387551,
    "lng": 127.4220556,
    "disability_types": [
      "뇌병변",
      "시각",
      "청각",
      "지체",
      "지적"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_26",
    "name": "동구아름다운복지관",
    "region": "대전",
    "district": "동구",
    "address": "대전광역시 동구 안골로 49",
    "phone": "042-282-9600",
    "website": "www.dbwc.or.kr",
    "org": "사)한국지체장애인협회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 36.2681199,
    "lng": 127.4722505,
    "disability_types": [
      "지체",
      "자폐성",
      "지적",
      "청각",
      "시각",
      "뇌병변"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_27",
    "name": "울산광역시장애인체육관",
    "region": "울산",
    "district": "남구",
    "address": "울산광역시 남구 삼산중로146번길 10",
    "phone": "052-269-4842",
    "website": "www.ugd.or.kr",
    "org": "사)울산광역시장애인총연합회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 35.5460789,
    "lng": 129.3368883,
    "disability_types": [
      "지체",
      "뇌병변",
      "청각",
      "자폐성",
      "지적"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_28",
    "name": "울산광역시제2장애인체육관",
    "region": "울산",
    "district": "중구",
    "address": "울산광역시 중구 종가로 350",
    "phone": "052-242-7330",
    "website": "www.2ugd.or.kr",
    "org": "사)울산광역시장애인총연합회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 35.5644481,
    "lng": 129.3155379,
    "disability_types": [
      "시각",
      "청각",
      "지적",
      "지체",
      "자폐성"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_29",
    "name": "광명시장애인종합복지관체육관",
    "region": "경기",
    "district": "광명시",
    "address": "경기도 광명시 목감로 120",
    "phone": "02-2616-3700",
    "website": "www.withlight.or.kr",
    "org": "재)성모성심수도회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.4789538,
    "lng": 126.8464263,
    "disability_types": [
      "자폐성",
      "지적",
      "지체",
      "시각",
      "뇌병변",
      "청각",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_30",
    "name": "홀트장애인종합체육관",
    "region": "경기",
    "district": "고양시",
    "address": "경기 도 고양시 일산서구 탄현로 42",
    "phone": "031-914-6635",
    "website": "www.holtgym.or.kr",
    "org": "사복)홀트아동복지회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.6962678,
    "lng": 126.7709999,
    "disability_types": [
      "뇌병변",
      "지체",
      "지적",
      "청각",
      "시각",
      "자폐성"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_31",
    "name": "고양시재활스포츠센터",
    "region": "경기",
    "district": "고양시",
    "address": "경기도 고양시 일산서구 탄현로139",
    "phone": "031-929-1500",
    "website": "www.gosports.or.kr",
    "org": "사복)홀트아동복지회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.7032101,
    "lng": 126.7645591,
    "disability_types": [
      "지적",
      "뇌병변",
      "기타"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_32",
    "name": "성분도복지관(체육관)",
    "region": "경기",
    "district": "광주시",
    "address": "경기도 광주시 도척면 도척윗로 278",
    "phone": "031-799-0318",
    "website": "www.bundoreh.com",
    "org": "재)부산성베네딕도수녀회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 37.3367828,
    "lng": 127.2936739,
    "disability_types": [
      "청각",
      "지적"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_33",
    "name": "명휘체육센터",
    "region": "경기",
    "district": "안산시",
    "address": "경기도 안산시 상록구 해안로 865",
    "phone": "031-406-1145",
    "website": "www.mhsc.or.kr",
    "org": "사복)명휘원",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.2834889,
    "lng": 126.8402396,
    "disability_types": [
      "뇌병변",
      "시각",
      "자폐성",
      "청각"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_34",
    "name": "수원시장애인종합복지관(수영장)",
    "region": "경기",
    "district": "수원시",
    "address": "경기도 수원시 영통구 창룡대로 255",
    "phone": "031-794-2266",
    "website": "www.suwonrehab.or.kr",
    "org": "사복)수원중앙복지재단",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 37.2955467,
    "lng": 127.0360454,
    "disability_types": [
      "청각",
      "시각",
      "지체",
      "자폐성"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_35",
    "name": "SRC재활체육관",
    "region": "경기",
    "district": "광주시",
    "address": "경기도 광주시 초월읍 경수길 25",
    "phone": "031-799-3891",
    "website": "www.srcsportscenter.com",
    "org": "사복) SRC",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.4187426,
    "lng": 127.2873314,
    "disability_types": [
      "지체",
      "지적",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_36",
    "name": "보훈재활체육센터",
    "region": "경기",
    "district": "수원시",
    "address": "경기도 수원시 장안구 광교산로 71",
    "phone": "031-259-0900",
    "website": "rsc.bohun.or.kr",
    "org": "보훈공단",
    "voucher": false,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 37.2975823,
    "lng": 127.0246089,
    "disability_types": [
      "지체",
      "뇌병변",
      "시각",
      "지적",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_37",
    "name": "성남시 한마음복지관",
    "region": "경기",
    "district": "성남시",
    "address": "경기 성남시 분당구 야탑로 227",
    "phone": "031-725-9500",
    "website": "www.woorimaum.org",
    "org": "분당우리복지재단",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.4082763,
    "lng": 127.1441876,
    "disability_types": [
      "지적",
      "자폐성",
      "지체",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_38",
    "name": "안양시수리장애인복지관",
    "region": "경기",
    "district": "안양시",
    "address": "경기 도 안양시 만안구 냉천로 39",
    "phone": "031-465-0950",
    "website": "www.asrc.or.kr",
    "org": "사복) 돕는사람들",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 37.3849761,
    "lng": 126.9269738,
    "disability_types": [
      "뇌병변",
      "시각",
      "정신",
      "기타"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_39",
    "name": "시흥어울림국민체육센터",
    "region": "경기",
    "district": "시흥시",
    "address": "경기도 시흥시 정왕대로233",
    "phone": "031-8084-0101",
    "website": "www.shsi.or.kr",
    "org": "시흥도시공사",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 37.3449671,
    "lng": 126.7385084,
    "disability_types": [
      "뇌병변",
      "시각",
      "지적",
      "청각",
      "지체",
      "자폐성",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_40",
    "name": "원주드림체육관",
    "region": "강원",
    "district": "원주시",
    "address": "강원특별자치도 원주시 현충로 53",
    "phone": "033-737-4666",
    "website": "www.wonju.go.krsports",
    "org": "원주시청",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.3603959,
    "lng": 127.9532676,
    "disability_types": [
      "지적",
      "청각",
      "시각",
      "지체",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_41",
    "name": "춘천장애인스포츠센터",
    "region": "강원",
    "district": "춘천시",
    "address": "강원특별자치도 춘천시 평화로 26",
    "phone": "033-240-1751",
    "website": "www.cuc.or.kr",
    "org": "춘천도시공사",
    "voucher": false,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 37.8855094,
    "lng": 127.7215926,
    "disability_types": [
      "지체",
      "자폐성",
      "시각",
      "지적"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_42",
    "name": "충주시장애인형국민체육센터",
    "region": "충북",
    "district": "충주시",
    "address": "충북 충주시 모시래길 105",
    "phone": "043-870-7850",
    "website": "www.cjfmc.or.kr",
    "org": "충주시시설관리공단",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 36.9591457,
    "lng": 127.9114263,
    "disability_types": [
      "지적",
      "청각",
      "지체",
      "자폐성",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_43",
    "name": "충청북도곰두리체육관",
    "region": "충북",
    "district": "청주시",
    "address": "충청북도 청주시 청원구 토성로 21",
    "phone": "043-216-0031",
    "website": "www.cbgomduri.or.kr",
    "org": "사)충청북도사회복지개발회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 36.6693164,
    "lng": 127.4648822,
    "disability_types": [
      "지적",
      "지체",
      "시각",
      "기타"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_44",
    "name": "제천시어울림체육센터",
    "region": "충북",
    "district": "제천시",
    "address": "충북 제천시 관전로 70",
    "phone": "043-653-9993",
    "website": "jcfmc.jecheon.go.kr",
    "org": "제천시청",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 37.1305633,
    "lng": 128.2299857,
    "disability_types": [
      "지체",
      "시각",
      "지적"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": true
  },
  {
    "id": "hwpc_45",
    "name": "청주시장애인스포츠센터",
    "region": "충북",
    "district": "청주시",
    "address": "충북 청주시 청원구 사천로 18",
    "phone": "043-211-4603",
    "website": "cjsad.or.kr",
    "org": "청주시장애인체육회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 36.634745,
    "lng": 127.488601,
    "disability_types": [
      "시각",
      "뇌병변"
    ],
    "geocode_source": "naver_district",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_46",
    "name": "보은군장애인회관",
    "region": "충북",
    "district": "보은군",
    "address": "충북 보은군 보은읍 뱃들4길 11-10",
    "phone": "043-544-3512",
    "website": "",
    "org": "보은군장애인단체연합회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 36.4883567,
    "lng": 127.7239,
    "disability_types": [
      "지적",
      "청각",
      "뇌병변",
      "지체"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_47",
    "name": "정심체육관",
    "region": "충남",
    "district": "보령시",
    "address": "충청남도 보령시 주교면 보령북로 404",
    "phone": "041-932-6076",
    "website": "www.jeongsim.or.kr",
    "org": "사복)보령학사",
    "voucher": true,
    "bandabi": false,
    "badge_type": "business",
    "lat": 36.3783653,
    "lng": 126.5868874,
    "disability_types": [
      "청각",
      "지체",
      "뇌병변"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_48",
    "name": "천안시장애인종합체육관",
    "region": "충남",
    "district": "천안시",
    "address": "충남 천안시 동남구 향교1길 104",
    "phone": "041-552-0014",
    "website": "casad.or.kr",
    "org": "천안시장애인체육회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 36.8158604,
    "lng": 127.171918,
    "disability_types": [
      "자폐성",
      "뇌병변",
      "시각",
      "지체",
      "청각",
      "기타"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_49",
    "name": "홍성군장애인스포츠센터",
    "region": "충남",
    "district": "홍성군",
    "address": "충남 홍성군 홍성읍 홍덕서로 78",
    "phone": "070-4401-1391",
    "website": "www.hscd.co.kr",
    "org": "홍성군장애인체육회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 36.6066597,
    "lng": 126.6438432,
    "disability_types": [
      "뇌병변",
      "자폐성",
      "청각",
      "지적",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_50",
    "name": "아산장애인국민체육센터",
    "region": "충남",
    "district": "아산시",
    "address": "충남 아산시 곡교천로27",
    "phone": "041-546-1513",
    "website": "www.asan.go.kr",
    "org": "아산시청",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 36.7878686,
    "lng": 126.9846214,
    "disability_types": [
      "지체",
      "뇌병변",
      "청각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_51",
    "name": "전라북도장애인복지관(체육관)",
    "region": "전북",
    "district": "전주시",
    "address": "전북특별자치도 전주시 완산구 천잠로 277",
    "phone": "063-222-9999",
    "website": "jbwcsports.cafe24.com",
    "org": "학교·사복)동암",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 35.81151,
    "lng": 127.0919909,
    "disability_types": [
      "시각",
      "지적",
      "청각",
      "자폐성"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_52",
    "name": "정읍곰두리스포츠센터",
    "region": "전북",
    "district": "정읍시",
    "address": "전북특별자치도 정읍시 수성1로 64",
    "phone": "063-539-5617",
    "website": "www.jjb.or.kr",
    "org": "정읍시",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 35.5773462,
    "lng": 126.854078,
    "disability_types": [
      "지체",
      "시각",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_53",
    "name": "김제시장애인체육관",
    "region": "전북",
    "district": "김제시",
    "address": "전북특별자치도 김제시 갈공길 32",
    "phone": "063-542-6500",
    "website": "www.grwc.or.kr",
    "org": "김제시장애인종합복지관",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 35.8050999,
    "lng": 126.8712005,
    "disability_types": [
      "지체",
      "자폐성",
      "청각",
      "뇌병변"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_54",
    "name": "군산시애인체육관",
    "region": "전북",
    "district": "군산시",
    "address": "전북특별자치도 군산시 대야면 석화로 63",
    "phone": "063-454-7707",
    "website": "",
    "org": "군산시",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 35.948843,
    "lng": 126.8166866,
    "disability_types": [
      "지적",
      "지체",
      "청각",
      "시각",
      "자폐성",
      "뇌병변",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": true
  },
  {
    "id": "hwpc_55",
    "name": "전주어울림국민체육센터",
    "region": "전북",
    "district": "전주시",
    "address": "전북 전주시 덕진구 조경단로 258",
    "phone": "063-239-2701",
    "website": "www.jjss.or.kr",
    "org": "전주시시설관리공단",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 35.8534313,
    "lng": 127.1259822,
    "disability_types": [
      "지적",
      "뇌병변",
      "시각",
      "자폐성",
      "지체",
      "청각"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_56",
    "name": "전라남도장애인종합복지관(체육관)",
    "region": "전남",
    "district": "나주시",
    "address": "전라남도 나주시 내영산1길 67",
    "phone": "061-332-4104",
    "website": "www.relife.or.kr",
    "org": "사)조선대 사회복지회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 35.0083147,
    "lng": 126.6951161,
    "disability_types": [
      "자폐성",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_57",
    "name": "여수시장애인국민체육센터",
    "region": "전남",
    "district": "여수시",
    "address": "전라남도 여수시 진남체육관길 74",
    "phone": "061-662-8204",
    "website": "www.yumcorp.or.kr",
    "org": "여수시도시관리공단",
    "voucher": false,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 34.7616209,
    "lng": 127.7274874,
    "disability_types": [
      "청각",
      "시각",
      "뇌병변",
      "지체"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_58",
    "name": "광양장애인국민체육센터",
    "region": "전남",
    "district": "광양시",
    "address": "전남 광양시 봉강면 매천로 695",
    "phone": "061-762-9880",
    "website": "",
    "org": "광양시장애인체육회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 34.9824091,
    "lng": 127.5736874,
    "disability_types": [
      "지적",
      "자폐성",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_59",
    "name": "해남군다목적생활체육관",
    "region": "전남",
    "district": "해남군",
    "address": "전라남도 해남군 해남읍 해남 로 72",
    "phone": "061-535-8226",
    "website": "",
    "org": "해남군청",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 34.5690833,
    "lng": 126.6208375,
    "disability_types": [
      "시각",
      "뇌병변",
      "청각",
      "자폐성"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_60",
    "name": "상주시장애인 종합복지관(체육관)",
    "region": "경북",
    "district": "상주시",
    "address": "경상북도 상주시 만산8길 11",
    "phone": "054-534-6933",
    "website": "www.sangjucrc.or.kr",
    "org": "사복)천주교안동교구사회복지회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 36.4422849,
    "lng": 128.154912,
    "disability_types": [
      "청각",
      "뇌병변",
      "자폐성",
      "시각",
      "지체"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_61",
    "name": "경주시장애인체육관",
    "region": "경북",
    "district": "경주시",
    "address": "경상북도 경주시 유림로5번길 99-11",
    "phone": "054-776-7522",
    "website": "www.gjrehab.or.kr",
    "org": "사복)대한불교조계종 불국사복지재단",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 35.8802071,
    "lng": 129.2183125,
    "disability_types": [
      "시각",
      "지체",
      "뇌병변",
      "자폐성",
      "청각",
      "지적",
      "기타"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_62",
    "name": "구미시장애인체육관",
    "region": "경북",
    "district": "구미시",
    "address": "경북 구미시 공원로 340",
    "phone": "054-451-7976",
    "website": "www.gumisports.kr",
    "org": "사)한국교통장애인협회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 36.1060236,
    "lng": 128.3305373,
    "disability_types": [
      "뇌병변",
      "청각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_63",
    "name": "애명체육관",
    "region": "경북",
    "district": "안동시",
    "address": "경북 안동시 북후면 광평2길 106-25",
    "phone": "054-852-2214",
    "website": "",
    "org": "사복)안동애명복지촌",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 36.6571154,
    "lng": 128.6818,
    "disability_types": [
      "청각",
      "지적",
      "뇌병변",
      "시각",
      "자폐성"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": true
  },
  {
    "id": "hwpc_64",
    "name": "문경시온누리체육관",
    "region": "경북",
    "district": "문경시",
    "address": "경북 문경시 점고길 21",
    "phone": "054-550-6435",
    "website": "www.gbmg.go.kr",
    "org": "문경시",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 36.5944296,
    "lng": 128.1855802,
    "disability_types": [
      "지체",
      "청각",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_65",
    "name": "창원시장애인종합복지관(체육관)",
    "region": "경남",
    "district": "창원시",
    "address": "경상남도 창원시 의창구 봉곡로97번길 87",
    "phone": "055-237-6485",
    "website": "www.cwrehab.or.kr",
    "org": "사복)범숙",
    "voucher": true,
    "bandabi": false,
    "badge_type": "instructor",
    "lat": 35.250421,
    "lng": 128.6795397,
    "disability_types": [
      "청각",
      "지체",
      "뇌병변",
      "지적",
      "자폐성",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": false
  },
  {
    "id": "hwpc_66",
    "name": "창원시립곰두리국민체육센터",
    "region": "경남",
    "district": "창원시",
    "address": "경남 창원시 의창구 원이대로114번길 6",
    "phone": "055-238-0220",
    "website": "www.cwgomduri.or.kr",
    "org": "사)경남지체장애인협회 창원시회",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 35.2530459,
    "lng": 128.6370113,
    "disability_types": [
      "지적",
      "시각",
      "청각",
      "자폐성",
      "뇌병변",
      "지체"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": false,
    "is_free": true
  },
  {
    "id": "hwpc_67",
    "name": "사천시장애인국민체육센터",
    "region": "경남",
    "district": "사천시",
    "address": "경상남도 사천시 용현면 진삼로 447",
    "phone": "055-831-5900",
    "website": "www.sacheon.go.kr",
    "org": "사천시청",
    "voucher": true,
    "bandabi": false,
    "badge_type": "public",
    "lat": 34.9968348,
    "lng": 128.0605048,
    "disability_types": [
      "청각",
      "시각",
      "뇌병변",
      "지적",
      "자폐성"
    ],
    "geocode_source": "naver_full",
    "verified_at": "2025-01-01",
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_68",
    "name": "제주특별자치도장애인스포츠센터(추후 개관예정)",
    "region": "제주",
    "district": "제주시",
    "address": "제주특별자치도 제주시 통물길 72",
    "phone": "064-797-7800",
    "website": "",
    "org": "제주특별자치도장애인체육회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 33.4865053,
    "lng": 126.4368679,
    "disability_types": [
      "시각",
      "청각",
      "지체"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_69",
    "name": "세종시장애인형국민체육센터",
    "region": "세종",
    "district": "세종시",
    "address": "세종특별자치시 시청대로 591",
    "phone": "044-850-4280",
    "website": "www.sjfmc.or.kr",
    "org": "세종특별자치시시설관리공단",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 36.4946651,
    "lng": 127.3192565,
    "disability_types": [
      "시각",
      "지적",
      "지체",
      "청각",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_70",
    "name": "광주북구반다비체육센터",
    "region": "광주",
    "district": "북구",
    "address": "광주광역시 북구 필문대로 55",
    "phone": "062-524-0731",
    "website": "www.gbfmc.or.kr",
    "org": "광주북구시설관리공단",
    "voucher": true,
    "bandabi": true,
    "badge_type": "business",
    "lat": 35.1647158,
    "lng": 126.9269526,
    "disability_types": [
      "자폐성",
      "뇌병변",
      "지체"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_71",
    "name": "홍천군장애인체육센터",
    "region": "강원",
    "district": "홍천군",
    "address": "강원특별자치도 홍천군 홍천읍 홍천 로 645",
    "phone": "033-433-7976",
    "website": "",
    "org": "홍천군장애인체육회",
    "voucher": false,
    "bandabi": false,
    "badge_type": "business",
    "lat": 37.7064278,
    "lng": 127.9071422,
    "disability_types": [
      "청각",
      "지체",
      "뇌병변",
      "자폐성",
      "시각"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": true
  },
  {
    "id": "hwpc_72",
    "name": "익산반다비체육센터",
    "region": "전북",
    "district": "익산시",
    "address": "전북특별자치도 익산시 무왕로 1397",
    "phone": "063-859-5872",
    "website": "",
    "org": "추후 선정 예정",
    "voucher": false,
    "bandabi": false,
    "badge_type": "public",
    "lat": 35.9680345,
    "lng": 127.0089392,
    "disability_types": [
      "지적",
      "청각"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": true,
    "is_free": false
  },
  {
    "id": "hwpc_73",
    "name": "양산반다비체육센터",
    "region": "경남",
    "district": "양산시",
    "address": "경상남도 양산시 물금읍 부산대학로 34",
    "phone": "055-379-8410",
    "website": "",
    "org": "양산시시설관리공단",
    "voucher": false,
    "bandabi": true,
    "badge_type": "public",
    "lat": 35.3230094,
    "lng": 129.0028701,
    "disability_types": [
      "청각",
      "자폐성",
      "뇌병변",
      "지적",
      "정신"
    ],
    "geocode_source": "naver_full",
    "verified_at": null,
    "has_weekend": false,
    "is_free": false
  }
];
